### ISSUE TITLE
require-from-string dependency error

### ISSUE THREAD

**Issue by jmeas** [davidtheclark/cosmiconfig#103]
Affected cosmiconfig version: `2.2.2`

---

require-from-string just published a new version, and it seems to have broken the version an older version of this lib depends on. I'm not too sure exactly what's going on, but I think it may be an npm error.

Travis build showing the error: https://travis-ci.org/jmeas/hearth/builds/325851628?utm_source=github_status&utm_medium=notification

To reproduce, just try to depend on `require-from-string@^1.1.0` and do an npm install. However, `npm info require-from-string` shows 1.1.0 as a valid version:

```
{ modified: '2018-01-06T18:57:39.402Z',
     created: '2015-07-18T15:08:53.362Z',
     '1.0.0': '2015-07-18T15:08:53.362Z',
     '1.0.1': '2015-11-03T08:09:49.990Z',
     '1.0.2': '2015-11-06T19:08:43.545Z',
     '1.1.0': '2015-11-07T11:43:15.008Z',
     '1.2.0': '2016-05-03T07:32:12.394Z',
     '1.2.1': '2016-10-01T19:32:05.278Z',
     '2.0.0': '2017-09-16T07:04:34.217Z',
     '2.0.1': '2017-09-17T06:52:37.555Z',
     '2.0.2': '2018-01-06T18:57:39.402Z' }
```
  
---

Cross-linking the npm issue: https://github.com/npm/npm/issues/19534

**Comment by JAertgeerts** [comment]
https://github.com/npm/registry/issues/255

**Comment by AndyGrom** [comment]
Now dependency require-from-string does not longer accessible at npm registry

**Comment by jmeas** [comment]
> Now dependency require-from-string does not longer accessible at npm registry

From what I'm seeing, the latest version (the one published in 2018) is, but versions prior to 2018 are unavailable.

**Comment by AndyGrom** [comment]
https://www.npmjs.com/package/require-from-string returns 404

**Comment by jmeas** [comment]
Correct @AndyGrom . You can still install v2.0.2, though (although the package _may_ have been hijacked due to this npm issue? That part isn't clear to me)

**Comment by AndyGrom** [comment]
Unfortunately, in my case I can not get a specific version. I have a deep dependence on the package of cosmiconfig. I do not even know what package it needs, maybe angular, maybe typescript.

**Comment by tbutter** [comment]
https://status.npmjs.org/

> Identified - Several packages including "require-from-string" are currently unavailable. We are aware of the issue and are working to restore the affected user and packages. Please do not attempt to republish packages, as this will hinder our progress in restoring them.

**Comment by Abhijit0324** [comment]
I am also facing the same issue.

**Comment by sudo-suhas** [comment]
The issue is resolved now - https://status.npmjs.org/incidents/41zfb8qpvrdj. Not sure what was the exact cause though. In any case, nothing to do here, closing the issue.

**Comment by nayanchandni** [comment]
Still facing the same issue? Is anyone else?

npm ERR! notarget No compatible version found: require-from-string@^1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

**Comment by jmeas** [comment]
@nayanchandni what is the output when you run `npm get registry`? Registries other than the main one may still be broken by this issue.

**Comment by nayanchandni** [comment]
Its an internal registry that caches all the packages. That could be the issue. I think it should be re-loaded. Thanks!

**Comment by jmeas** [comment]
Our internal registry's normal sync script was not enough to fix this issue, and we had to go in and manually fix things.

For future users: if you're not using the public registry, you may need to do some manual fixing as well.
